In [5]:
#kütüphaneleri import edelim
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter

#Python'da uyarıları kapatıyoruz
import warnings
warnings.filterwarnings("ignore")

In [6]:
#Veriyi içeri aktarıyoruz
file_path = "online_sales_dataset.csv"
veri = pd.read_csv(file_path)
veri.head()

InvoiceNo StockCode Description  Quantity       InvoiceDate  UnitPrice  \
0     221958  SKU_1964   White Mug        38  2020-01-01 00:00       1.71   
1     771155  SKU_1241   White Mug        18  2020-01-01 01:00      41.25   
2     231932  SKU_1501  Headphones        49  2020-01-01 02:00      29.11   
3     465838  SKU_1760   Desk Lamp        14  2020-01-01 03:00      76.68   
4     359178  SKU_1386   USB Cable       -30  2020-01-01 04:00     -68.11   

   CustomerID         Country  Discount  PaymentMethod  ShippingCost  \
0     37039.0       Australia  0.470000  Bank Transfer         10.79   
1     19144.0           Spain  0.190000        paypall          9.51   
2     50472.0         Germany  0.350000  Bank Transfer         23.03   
3     96586.0     Netherlands  0.140000        paypall         11.08   
4         NaN  United Kingdom  1.501433  Bank Transfer           NaN   

      Category SalesChannel  ReturnStatus ShipmentProvider WarehouseLocation  \
0      Apparel     In-store  Not Returned              UPS            London   
1  Electronics       Online  Not Returned              UPS              Rome   
2  Electronics       Online      Returned              UPS            Berlin   
3  Accessories       Online  Not Returned       Royal Mail              Rome   
4  Electronics     In-store  Not Returned            FedEx               NaN   

  OrderPriority  
0        Medium  
1        Medium  
2          High  
3           Low  
4        Medium

In [7]:
veri.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49782 entries, 0 to 49781
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   InvoiceNo          49782 non-null  int64  
 1   StockCode          49782 non-null  object 
 2   Description        49782 non-null  object 
 3   Quantity           49782 non-null  int64  
 4   InvoiceDate        49782 non-null  object 
 5   UnitPrice          49782 non-null  float64
 6   CustomerID         44804 non-null  float64
 7   Country            49782 non-null  object 
 8   Discount           49782 non-null  float64
 9   PaymentMethod      49782 non-null  object 
 10  ShippingCost       47293 non-null  float64
 11  Category           49782 non-null  object 
 12  SalesChannel       49782 non-null  object 
 13  ReturnStatus       49782 non-null  object 
 14  ShipmentProvider   49782 non-null  object 
 15  WarehouseLocation  46297 non-null  object 
 16  OrderPriority      497

In [8]:
veri.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Discount', 'PaymentMethod',
       'ShippingCost', 'Category', 'SalesChannel', 'ReturnStatus',
       'ShipmentProvider', 'WarehouseLocation', 'OrderPriority'],
      dtype='object')

In [9]:
#drop fonksiyonu sütunları çıkaralım
veri = veri.drop(["InvoiceNo","StockCode","InvoiceDate","Country","PaymentMethod","Category","SalesChannel","ShipmentProvider","WarehouseLocation"],axis=1) #axis=1 sütun manasında
veri.head(2)

Description  Quantity  UnitPrice  CustomerID  Discount  ShippingCost  \
0   White Mug        38       1.71     37039.0      0.47         10.79   
1   White Mug        18      41.25     19144.0      0.19          9.51   

   ReturnStatus OrderPriority  
0  Not Returned        Medium  
1  Not Returned        Medium

In [10]:
essiz_description=pd.unique(veri.Description)
print("eşsiz description sayısı: {}".format(len(essiz_description)))
essiz_description[:10]

eşsiz description sayısı: 11


array(['White Mug', 'Headphones', 'Desk Lamp', 'USB Cable',
       'Office Chair', 'Notebook', 'Wireless Mouse', 'Blue Pen',
       'Wall Clock', 'T-shirt'], dtype=object)

In [11]:
essiz_order_priority=pd.unique(veri.OrderPriority)
print("eşsiz order_priority sayısı: {}".format(len(essiz_order_priority)))
essiz_order_priority[:10]

eşsiz order_priority sayısı: 3


array(['Medium', 'High', 'Low'], dtype=object)

In [13]:
essiz_quantity=pd.unique(veri.Quantity)
print("eşsiz essiz_quantity sayısı: {}".format(len(essiz_quantity)))
essiz_quantity[:10]

eşsiz essiz_quantity sayısı: 99


array([ 38,  18,  49,  14, -30,  47,  25,   8,  19,  40], dtype=int64)

In [20]:
essiz_UnitPrice=pd.unique(veri.UnitPrice)
print("eşsiz essiz_UnitPrice sayısı: {}".format(len(essiz_UnitPrice)))
essiz_UnitPrice[:100]

eşsiz essiz_UnitPrice sayısı: 11200


array([  1.71,  41.25,  29.11,  76.68, -68.11,  70.16,  85.74,  95.65,
        98.19,  98.17,  87.56,  59.51,  25.59,   2.09,  35.88,  82.58,
        70.85,  14.91,   1.07,  27.03,  77.17,  66.89,  66.18,  70.01,
        27.87,  59.53,  97.96,  28.73,  86.71,  90.69,  40.36,   8.39,
        99.31,  10.32,  82.94,  35.39,  61.34,  30.77,  38.11,  29.06,
        21.32,  36.85,  86.68,   9.08,   2.1 ,  24.36,  84.83,  93.1 ,
        81.47,   4.74,  20.35,  33.63,  68.66,  33.4 ,  49.95,   5.04,
         4.66,  73.48,  11.4 ,  28.29,   1.47,  55.33,  54.79,  45.18,
        78.9 ,  39.  ,  25.56,  34.13,  69.38,  94.81,  70.77,  99.17,
        61.05,  94.77,  15.02,  24.56,  66.41,  49.41,  36.99,  36.14,
        30.82,  81.28,  36.13,   8.62,  15.96,  49.92,  13.63,  83.42,
        91.57,   7.54,  87.27,  68.95,  33.22,  25.98,  41.15,  60.36,
        24.81,  88.14,   3.75,   7.96])

In [23]:
essiz_CustomerID=pd.unique(veri.CustomerID)
print("eşsiz essiz_CustomerID sayısı: {}".format(len(essiz_CustomerID)))
essiz_CustomerID[:10]

eşsiz essiz_CustomerID sayısı: 35390


array([37039., 19144., 50472., 96586.,    nan, 53887., 46567., 75098.,
       87950., 39718.])

In [25]:
essiz_Discount=pd.unique(veri.Discount)
print("eşsiz essiz_Discount sayısı: {}".format(len(essiz_Discount)))
essiz_Discount[:10]

eşsiz essiz_Discount sayısı: 1047


array([0.47      , 0.19      , 0.35      , 0.14      , 1.50143304,
       0.48      , 0.15      , 0.04      , 0.05      , 0.16      ])

In [27]:
essiz_ShippingCost=pd.unique(veri.ShippingCost)
print("eşsiz essiz_ShippingCost sayısı: {}".format(len(essiz_ShippingCost)))
essiz_ShippingCost[:10]

eşsiz essiz_ShippingCost sayısı: 2502


array([10.79,  9.51, 23.03, 11.08,   nan, 13.98, 12.92,  6.48, 12.56,
        7.71])

In [29]:
essiz_ReturnStatus=pd.unique(veri.ReturnStatus)
print("eşsiz essiz_ReturnStatus sayısı: {}".format(len(essiz_ReturnStatus)))
essiz_ReturnStatus[:10]

eşsiz essiz_ReturnStatus sayısı: 2


array(['Not Returned', 'Returned'], dtype=object)

In [31]:
Description_degiskeni=veri["Description"]
pd.isnull(Description_degiskeni).sum()

0

In [33]:
Quantity_degiskeni=veri["Quantity"]
pd.isnull(Quantity_degiskeni).sum()

0

In [35]:
UnitPrice_degiskeni=veri["UnitPrice"]
pd.isnull(UnitPrice_degiskeni).sum()

0

In [37]:
CustomerID_degiskeni=veri["CustomerID"]
pd.isnull(CustomerID_degiskeni).sum()

4978

In [39]:
Discount_degiskeni=veri["Discount"]
pd.isnull(Discount_degiskeni).sum()

0

In [41]:
ShippingCost_degiskeni=veri["ShippingCost"]
pd.isnull(ShippingCost_degiskeni).sum()

2489

In [43]:
ReturnStatus_degiskeni=veri["ReturnStatus"]
pd.isnull(ReturnStatus_degiskeni).sum()

0

In [45]:
OrderPriority_degiskeni=veri["OrderPriority"]
pd.isnull(OrderPriority_degiskeni).sum()

0

In [47]:
veri.describe()

Quantity     UnitPrice    CustomerID      Discount  ShippingCost
count  49782.000000  49782.000000  44804.000000  49782.000000  47293.000000
mean      22.372343     47.537862  55032.871775      0.275748     17.494529
std       17.917774     33.479510  25913.660157      0.230077      7.220557
min      -50.000000    -99.980000  10001.000000      0.000000      5.000000
25%       11.000000     23.592500  32750.750000      0.130000     11.220000
50%       23.000000     48.920000  55165.000000      0.260000     17.500000
75%       37.000000     74.610000  77306.250000      0.380000     23.720000
max       49.000000    100.000000  99998.000000      1.999764     30.000000

In [49]:
veri[["Description","UnitPrice","Discount","ShippingCost"]].groupby(["Description"], as_index=False).sum()[:20]

Description  UnitPrice     Discount  ShippingCost
0         Backpack  218657.88  1231.359593      75499.40
1         Blue Pen  213825.87  1243.041017      74560.84
2        Desk Lamp  217030.62  1246.106211      75769.19
3       Headphones  215603.89  1262.531267      75420.18
4         Notebook  211464.47  1233.794535      74734.37
5     Office Chair  212763.33  1261.655297      74442.13
6          T-shirt  212974.23  1227.291127      74949.44
7        USB Cable  215050.15  1252.009151      77176.50
8       Wall Clock  215009.72  1298.063054      76028.85
9        White Mug  221052.98  1233.194621      75129.23
10  Wireless Mouse  213096.69  1238.224537      73658.64

In [51]:
veri['Quantity'] = veri['Quantity'].abs()

In [53]:
print((veri['Quantity'] < 0).sum())  # Hangi sütunda kaç negatif değer kaldığını gösterir

0


In [55]:
veri['UnitPrice'] = veri['UnitPrice'].abs()

In [57]:
print((veri['UnitPrice'] < 0).sum())  # Hangi sütunda kaç negatif değer kaldığını gösterir

0


In [59]:
veri.describe()

Quantity     UnitPrice    CustomerID      Discount  ShippingCost
count  49782.000000  49782.000000  44804.000000  49782.000000  47293.000000
mean      24.925555     50.625031  55032.871775      0.275748     17.494529
std       14.152125     28.597658  25913.660157      0.230077      7.220557
min        1.000000      1.000000  10001.000000      0.000000      5.000000
25%       13.000000     25.862500  32750.750000      0.130000     11.220000
50%       25.000000     50.555000  55165.000000      0.260000     17.500000
75%       37.000000     75.370000  77306.250000      0.380000     23.720000
max       50.000000    100.000000  99998.000000      1.999764     30.000000

In [61]:
# Null olan değerlerin hangi grupta olduğunu bulup, o grubun ortalamasını o değere atama
for index, row in veri[veri['ShippingCost'].isnull()].iterrows():
    description = row['Description']  # Null değerin bulunduğu satırın Descriptionu
    mean_value = veri[veri['Description'] == description]['ShippingCost'].mean()  # O description için ortalama hesaplama
    veri.at[index, 'ShippingCost'] = mean_value  # Null değeri ortalama ile doldur

In [62]:
ShippingCost_degiskeni=veri["ShippingCost"]
pd.isnull(ShippingCost_degiskeni).sum()

0

In [63]:
# Null olan değerlerin hangi grupta olduğunu bulup, o grubun ortalamasını o değere atama
max=99999.000000
for index, row in veri[veri['CustomerID'].isnull()].iterrows():
    veri.at[index, 'CustomerID'] = max
    max=max+1

In [64]:
CustomerID_degiskeni=veri["CustomerID"]
pd.isnull(CustomerID_degiskeni).sum()

0

In [65]:
veri.describe()

Quantity     UnitPrice     CustomerID      Discount  ShippingCost
count  49782.000000  49782.000000   49782.000000  49782.000000  49782.000000
mean      24.925555     50.625031   59778.143948      0.275748     17.494694
std       14.152125     28.597658   28412.065100      0.230077      7.037785
min        1.000000      1.000000   10001.000000      0.000000      5.000000
25%       13.000000     25.862500   35163.250000      0.130000     11.540000
50%       25.000000     50.555000   60118.500000      0.260000     17.471214
75%       37.000000     75.370000   84860.500000      0.380000     23.410000
max       50.000000    100.000000  104976.000000      1.999764     30.000000

In [66]:
veri.head()

Description  Quantity  UnitPrice  CustomerID  Discount  ShippingCost  \
0   White Mug        38       1.71     37039.0  0.470000     10.790000   
1   White Mug        18      41.25     19144.0  0.190000      9.510000   
2  Headphones        49      29.11     50472.0  0.350000     23.030000   
3   Desk Lamp        14      76.68     96586.0  0.140000     11.080000   
4   USB Cable        30      68.11     99999.0  1.501433     17.705093   

   ReturnStatus OrderPriority  
0  Not Returned        Medium  
1  Not Returned        Medium  
2      Returned          High  
3  Not Returned           Low  
4  Not Returned        Medium

In [67]:
veri['ReturnStatus'] = veri['ReturnStatus'].map({'Returned': 0, 'Not Returned': 1})

In [68]:
veri.head()

Description  Quantity  UnitPrice  CustomerID  Discount  ShippingCost  \
0   White Mug        38       1.71     37039.0  0.470000     10.790000   
1   White Mug        18      41.25     19144.0  0.190000      9.510000   
2  Headphones        49      29.11     50472.0  0.350000     23.030000   
3   Desk Lamp        14      76.68     96586.0  0.140000     11.080000   
4   USB Cable        30      68.11     99999.0  1.501433     17.705093   

   ReturnStatus OrderPriority  
0             1        Medium  
1             1        Medium  
2             0          High  
3             1           Low  
4             1        Medium

In [95]:
# Normalize işlemleri

# Her bir Description için normalize edilmiş UnitPrice_Contribution hesaplama
def calculate_unitprice_contribution(group):
    group['UnitPrice_Contribution'] = group['UnitPrice'] / group['UnitPrice'].max()
    return group
# Gruplayarak UnitPrice_Contribution hesaplama
veri = veri.groupby('Description', group_keys=False).apply(calculate_unitprice_contribution)

veri['Quantity_Contribution'] = veri['Quantity'] / 50
veri['Discount_Contribution'] = 1 - (veri['Discount'] / 2)+0.1
veri['Shipping_Contribution'] = 1 - (veri['ShippingCost'] - 5) / (30 - 5)+0.1
veri['Return_Contribution'] = veri['ReturnStatus']

# OrderPriority puanlama
priority_mapping = {'High': 1.0, 'Medium': 0.5, 'Low': 0.2}
veri['Priority_Contribution'] = veri['OrderPriority'].map(priority_mapping)

# Rating hesaplama
weights = [-0.2, 0.05, -0.2, 0.2, 0.2, 0.2]
veri['Rating'] = (
    weights[0] * veri['UnitPrice_Contribution'] +
    weights[1] * veri['Quantity_Contribution'] +
    weights[2] * veri['Discount_Contribution']+0.2+
    weights[3] * veri['Shipping_Contribution'] +
    weights[4] * veri['Return_Contribution'] +
    weights[5] * veri['Priority_Contribution']
)
veri.head(10)

Description  Quantity  UnitPrice  CustomerID  Discount  ShippingCost  \
0       White Mug        38       1.71     37039.0  0.470000     10.790000   
1       White Mug        18      41.25     19144.0  0.190000      9.510000   
2      Headphones        49      29.11     50472.0  0.350000     23.030000   
3       Desk Lamp        14      76.68     96586.0  0.140000     11.080000   
4       USB Cable        30      68.11     99999.0  1.501433     17.705093   
5    Office Chair        47      70.16     53887.0  0.480000     13.980000   
6       USB Cable        25      85.74     46567.0  0.150000     12.920000   
7        Notebook         8      95.65     75098.0  0.040000      6.480000   
8  Wireless Mouse        19      98.19     87950.0  0.050000     12.560000   
9      Headphones        40      98.17     39718.0  0.160000      7.710000   

   ReturnStatus OrderPriority  Quantity_Contribution  Discount_Contribution  \
0             1        Medium                   0.76               0.865000   
1             1        Medium                   0.36               1.005000   
2             0          High                   0.98               0.925000   
3             1           Low                   0.28               1.030000   
4             1        Medium                   0.60               0.349283   
5             1        Medium                   0.94               0.860000   
6             1          High                   0.50               1.025000   
7             1           Low                   0.16               1.080000   
8             1          High                   0.38               1.075000   
9             1           Low                   0.80               1.020000   

   Shipping_Contribution  Return_Contribution  Priority_Contribution  \
0               0.868400                    1                    0.5   
1               0.919600                    1                    0.5   
2               0.378800                    0                    1.0   
3               0.856800                    1                    0.2   
4               0.591796                    1                    0.5   
5               0.740800                    1                    0.5   
6               0.783200                    1                    1.0   
7               1.040800                    1                    0.2   
8               0.797600                    1                    1.0   
9               0.991600                    1                    0.2   

     Rating  UnitPrice_Contribution  
0  0.535260                0.017102  
1  0.418412                0.412541  
2  0.281505                0.291275  
3  0.266000                0.766800  
4  0.442255                0.681236  
5  0.382812                0.701740  
6  0.405126                0.857572  
7  0.248764                0.956978  
8  0.367120                0.981998  
9  0.277862                0.982289

In [97]:
veri.describe()

Quantity     UnitPrice     CustomerID      Discount  ShippingCost  \
count  49782.000000  49782.000000   49782.000000  49782.000000  49782.000000   
mean      24.925555     50.625031   59778.143948      0.275748     17.494694   
std       14.152125     28.597658   28412.065100      0.230077      7.037785   
min        1.000000      1.000000   10001.000000      0.000000      5.000000   
25%       13.000000     25.862500   35163.250000      0.130000     11.540000   
50%       25.000000     50.555000   60118.500000      0.260000     17.471214   
75%       37.000000     75.370000   84860.500000      0.380000     23.410000   
max       50.000000    100.000000  104976.000000      1.999764     30.000000   

       ReturnStatus  Quantity_Contribution  Discount_Contribution  \
count  49782.000000           49782.000000           49782.000000   
mean       0.901691               0.498511               0.962126   
std        0.297734               0.283042               0.115038   
min        0.000000               0.020000               0.100118   
25%        1.000000               0.260000               0.910000   
50%        1.000000               0.500000               0.970000   
75%        1.000000               0.740000               1.035000   
max        1.000000               1.000000               1.100000   

       Shipping_Contribution  Return_Contribution  Priority_Contribution  \
count           49782.000000         49782.000000           49782.000000   
mean                0.600212             0.901691               0.566659   
std                 0.281511             0.297734               0.329602   
min                 0.100000             0.000000               0.200000   
25%                 0.363600             1.000000               0.200000   
50%                 0.601151             1.000000               0.500000   
75%                 0.838400             1.000000               1.000000   
max                 1.100000             1.000000               1.000000   

             Rating  UnitPrice_Contribution  
count  49782.000000            49782.000000  
mean       0.344941                0.506361  
std        0.122395                0.286039  
min       -0.130279                0.010000  
25%        0.266062                0.258700  
50%        0.348426                0.505701  
75%        0.430767                0.753895  
max        0.712265                1.000000

In [99]:
veri['Rating'] = veri['Rating'] + 0.2

In [105]:
veri.describe()

Quantity     UnitPrice     CustomerID      Discount  ShippingCost  \
count  49782.000000  49782.000000   49782.000000  49782.000000  49782.000000   
mean      24.925555     50.625031   59778.143948      0.275748     17.494694   
std       14.152125     28.597658   28412.065100      0.230077      7.037785   
min        1.000000      1.000000   10001.000000      0.000000      5.000000   
25%       13.000000     25.862500   35163.250000      0.130000     11.540000   
50%       25.000000     50.555000   60118.500000      0.260000     17.471214   
75%       37.000000     75.370000   84860.500000      0.380000     23.410000   
max       50.000000    100.000000  104976.000000      1.999764     30.000000   

       ReturnStatus  Quantity_Contribution  Discount_Contribution  \
count  49782.000000           49782.000000           49782.000000   
mean       0.901691               0.498511               0.962126   
std        0.297734               0.283042               0.115038   
min        0.000000               0.020000               0.100118   
25%        1.000000               0.260000               0.910000   
50%        1.000000               0.500000               0.970000   
75%        1.000000               0.740000               1.035000   
max        1.000000               1.000000               1.100000   

       Shipping_Contribution  Return_Contribution  Priority_Contribution  \
count           49782.000000         49782.000000           49782.000000   
mean                0.600212             0.901691               0.566659   
std                 0.281511             0.297734               0.329602   
min                 0.100000             0.000000               0.200000   
25%                 0.363600             1.000000               0.200000   
50%                 0.601151             1.000000               0.500000   
75%                 0.838400             1.000000               1.000000   
max                 1.100000             1.000000               1.000000   

             Rating  UnitPrice_Contribution  
count  49782.000000            49782.000000  
mean       0.544941                0.506361  
std        0.122395                0.286039  
min        0.069721                0.010000  
25%        0.466062                0.258700  
50%        0.548426                0.505701  
75%        0.630767                0.753895  
max        0.912265                1.000000

In [109]:
df = pd.DataFrame(veri)

# User-Product matrisini oluşturma (ortalama ile toplulaştırma)
user_product_matrix = df.pivot_table(index='CustomerID', columns='Description', values='Rating', aggfunc='mean')


In [111]:
user_product_matrix

Description  Backpack  Blue Pen  Desk Lamp  Headphones  Notebook  \
CustomerID                                                         
10001.0           NaN       NaN        NaN         NaN       NaN   
10003.0           NaN       NaN        NaN         NaN       NaN   
10005.0           NaN  0.448714        NaN         NaN       NaN   
10008.0           NaN       NaN        NaN         NaN       NaN   
10009.0           NaN       NaN        NaN         NaN       NaN   
...               ...       ...        ...         ...       ...   
104972.0          NaN       NaN   0.560589         NaN       NaN   
104973.0          NaN       NaN        NaN         NaN       NaN   
104974.0          NaN       NaN        NaN         NaN       NaN   
104975.0          NaN       NaN        NaN         NaN       NaN   
104976.0          NaN       NaN        NaN         NaN       NaN   

Description  Office Chair   T-shirt  USB Cable  Wall Clock  White Mug  \
CustomerID                                                              
10001.0          0.640027       NaN        NaN         NaN        NaN   
10003.0               NaN       NaN    0.50843         NaN        NaN   
10005.0               NaN       NaN        NaN         NaN        NaN   
10008.0               NaN  0.659557        NaN         NaN        NaN   
10009.0          0.575130       NaN        NaN         NaN        NaN   
...                   ...       ...        ...         ...        ...   
104972.0              NaN       NaN        NaN         NaN        NaN   
104973.0              NaN       NaN        NaN         NaN   0.741385   
104974.0              NaN       NaN        NaN         NaN   0.749125   
104975.0              NaN       NaN        NaN     0.60518        NaN   
104976.0         0.571888       NaN        NaN         NaN        NaN   

Description  Wireless Mouse  
CustomerID                   
10001.0                 NaN  
10003.0                 NaN  
10005.0                 NaN  
10008.0                 NaN  
10009.0                 NaN  
...                     ...  
104972.0                NaN  
104973.0                NaN  
104974.0                NaN  
104975.0                NaN  
104976.0                NaN  

[40367 rows x 11 columns]

In [113]:
# User-Product matrisini CSV dosyası olarak kaydetme
user_product_matrix.to_csv('user_product_matrix_tek.csv', index=True)